# Generated by Django 4.0.5 on 2022-11-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'phone')},
        ),
    ]
