# Generated by Django 4.0.5 on 2022-11-22 08:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyhistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
