# Generated by Django 4.0.5 on 2022-12-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_category_id_alter_favoriteproduct_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='items',
            field=models.ManyToManyField(blank=True, to='items.item'),
        ),
    ]
